name: Terminus Rsync Plugin
on: push
jobs:
  checkout_lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    name: Checkout & lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save repo content as artifact
        uses: actions/upload-artifact@v2
        with:
          name: full-workspace
          path: ${{ github.workspace }}
      - name: Full Composer Install
        run: composer install
      - name: Install phpcs
        run: composer install-phpcs
      - name: Validate Code
        run: composer cs

  test:
    runs-on: ubuntu-latest
    container:
      image: pantheonpublic/terminus-plugin-test:4.x-php8.0
      options: --user root
    name: Test
    needs: [ checkout_lint ]
    defaults:
      run:
        shell: bash
        working-directory: /terminus-plugin-test/plugin
    env:
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      TERMINUS_SITE: ${{ secrets.TERMINUS_SITE }}
      BASH_ENV: ~/.bashrc
      HOME: /terminus-plugin-test
    steps:
      - name: Download repo content from artifact
        uses: actions/download-artifact@v2
        with:
          name: full-workspace
          path: /terminus-plugin-test/plugin
      - name: Setup environment
        run: chmod +x ./.ci/set-up-globals.sh && ./.ci/set-up-globals.sh
      - name: Check Terminus version
        run: terminus --version
      - name: Install plugin
        run: terminus self:plugin:install .
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
      - name: Run tests
        run: composer bats
